config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    # Redirests signing out users back to sign-in
    root to: "devise/sessions#new"
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  
  scope '/admin', shallow_prefix: "admin", module: 'admin' do
    resources :dashboard, shallow: true
    resources :users, shallow: true
    post 'import-csv', to: 'users#import_csv'
  end

  scope '/client', shallow_prefix: "client", module: 'client' do
    resources :dashboard, shallow: true
    resources :users, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  enum user_type: {
    client: 0,
    admin: 1
  }

  validates :email, :fullname, :password, :avatar_image, :user_type, presence: true
  validates :email, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ApplicationController
    include Pundit
    before_action :admin_authenticate

    layout "admin"

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    protected

    def admin_authenticate
      authorize current_user, :admin?
    end

    private

    def user_not_authorized(exception)
      render json: {error: exception.message }
    end
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < Admin::ApplicationController
    def index
      @clients = User.where(user_type: 'client').count
      @admins = User.where(user_type: 'admin').count
      @total = @clients + @admins

      respond_to do |format|
        format.html
        format.json { render json: { 
          clients: @clients,
          admins: @admins,
          total: @total
        }}
      end
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    skip_before_action :verify_authenticity_token, only: [:import_csv]

    def index
      respond_to do |format|
        format.html
        format.json { render json: Users::SearchUserService.new(params['type']).call }
      end
    end

    def new
      @user = User.new
    end

    def create
      response = Users::CreateUserService.new(params).call
      if response
        flash[:notice] = "created success"
        redirect_to dashboard_index_path
      else
        render 'new', status: :unprocessable_entify
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      if Users::UpdateUserService.new(params).call
        flash[:notice] = "Upload success"
        redirect_to dashboard_index_path
      else
        render 'edit', status: :unprocessable_entify
      end
    end

    def destroy
      if Users::DeleteUserService.new(params[:id]).call
        flash[:notice] = "Delete success"
        redirect_to dashboard_index_path
      else
        redirect_to dashboard_index_path, status: :unprocessable_entify
      end
    end

    def import_csv
      if Users::ImportUsersService.new(params[:file]).call
        render json: {success: true}
      else
        render json: {success: false}
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
 
  protected 
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :avatar_image]) 
  end

  def after_sign_in_path_for(resource)
    if resource.admin?
      dashboard_index_path
    else
      '/client/dashboard'
    end
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
    err_message = t "#{policy_name}.#{exception.query}", scope: 'pundit', default: :default
    render json: { message: err_message }, status: :unauthorized
  end
end

app/controllers/client/application_controller.rb
module Client
  class ApplicationController < ApplicationController
    include Pundit
    before_action :client_authenticate

    layout "admin"

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    protected

    def client_authenticate
      authorize current_user, :client?
    end

    private

    def user_not_authorized(exception)
      render json: {error: exception.message }
    end
  end
end

app/controllers/client/dashboard_controller.rb
module Client
  class DashboardController < Client::ApplicationController
    def index
      @clients = User.where(user_type: 'client').count
      @admins = User.where(user_type: 'admin').count
      @total = @clients + @admins

      respond_to do |format|
        format.html
        format.json { render json: { 
          clients: @clients,
          admins: @admins,
          total: @total
        }}
      end
    end
  end
end

app/controllers/client/users_controller.rb
module Client
  class UsersController < Client::ApplicationController
    def edit
      @user = authorize User.find(params[:id])
    end

    def update
      if Users::UpdateUserService.new(params).call
        flash[:notice] = "Upload success"
        redirect_to '/client/dashboard'
      else
        render 'edit', status: :unprocessable_entify
      end
    end

    def destroy
      if Users::DeleteUserService.new(params[:id]).call
        flash[:notice] = "Delete success"
        redirect_to '/client/dashboard'
      else
        redirect_to '/client/dashboard', status: :unprocessable_entify
      end
    end
  end
end

app/controllers/turbo_devise_controller.rb
# frozen_string_literal: true

class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.erb
<div data-controller="users" >
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-3 mb-md-0">
      <div class="btn-group me-3">
        <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->users#allUser">all</button>
        <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->users#clientUser">Clients</button>
        <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->users#adminUser">Administrators </button>
      </div>
      <div class="btn-group me-2">
        <a href="<%= new_user_path %>" class="btn btn-sm btn-outline-secondary">Create user</a>
        <label for="customFile" class="btn btn-sm btn-outline-secondary">Import CSV</label>
      </div>
    </div>
  </div>
  <input type="file" class="btn btn-sm btn-outline-secondary" style="visibility:hidden;" id="customFile" data-action="change->users#importFile">

  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm border-primary" data-action="click->users#allUser" style="cursor: pointer">
        <div class="card-header py-3 text-white bg-primary border-primary">
          <h4 class="my-0 fw-normal">Total</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title" data-users-target="total"></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Users</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm" data-action="click->users#clientUser" style="cursor: pointer">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal">Clients</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title" data-users-target="clients"></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Clients</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card mb-4 rounded-3 shadow-sm" data-action="click->users#adminUser"  style="cursor: pointer">
        <div class="card-header py-3 ">
          <h4 class="my-0 fw-normal">Administrator</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title" data-users-target="admins"></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Admin</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <h2>Users</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Avatar</th>
          <th scope="col">Role</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody data-users-target="list"></tbody>
    </table>
  </div>
</div>

app/views/admin/users/_form.html.erb
<%= form_for(@user, url: (@user.id.present? ? admin_user_path(@user) : '/admin/users')) do |f| %>
  <div class="row">
    <div class="form-outline mb-4 col-sm-6">
      <%= f.text_field :fullname, class: 'form-control form-control-lg', required: true %>
      <%= f.label :fullname, class: 'form-label' %>
    </div>

    <div class="form-outline mb-4 col-sm-6">
      <%= f.select(:user_type, User.user_types.keys.map { |t| [t.humanize, t] }, {}, {class: 'form-select form-control form-control-lg'}) %>
      <%= f.label :user_type, class: 'form-label' %>
    </div>
  </div>

  <div class="row">
    <div class="form-outline mb-4 col-sm-6">
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control form-control-lg', required: true %>
      <%= f.label :email, class: 'form-label' %>
    </div>

    <div class="form-outline mb-4 col-sm-6">
      <%= f.text_field :avatar_image, class: 'form-control form-control-lg', required: true %>
      <%= f.label :avatar_image, class: 'form-label' %>
    </div>
  </div>

  <div class="row">
    <div class="form-outline mb-4 col-sm-6">
      <% if @user.id.present? %>
        <%= f.password_field :password, autocomplete: "new-password", class: 'form-control form-control-lg' %>
      <% else %>
        <%= f.password_field :password, autocomplete: "new-password", class: 'form-control form-control-lg', required: true %>
      <% end %>
      <%= f.label :password, class: 'form-label' %> <%= "<i>(leave blank if you don't want to change it)</i>".html_safe if @user.id.present? %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
    </div>

    <div class="form-outline mb-4 col-sm-6">
      <% if @user.id.present? %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control form-control-lg' %>
      <% else %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control form-control-lg', required: true %>
      <% end %>
      
      <%= f.label :password_confirmation, class: 'form-label' %>
    </div>
  </div>
  <div class="pt-1 mb-4">
    <%= f.submit nil, class: 'btn btn-dark btn-lg btn-block' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">User <%= @user.fullname %></h1>
</div>
  
<h4 class="mb-3">Edit user</h4>
  
<%= render "form" %>

app/views/admin/users/index.html.erb
<div data-controller="users">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Users</h1>
    <div class="btn-toolbar mb-3 mb-md-0">
      <div class="btn-group me-3">
        <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->users#allUser">all</button>
        <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->users#clientUser">Clients</button>
        <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->users#adminUser">Administrators </button>
      </div>
      <div class="btn-group me-2">
        <a href="<%= new_user_path %>" class="btn btn-sm btn-outline-secondary">Create user</a>
        <label for="customFile" class="btn btn-sm btn-outline-secondary">Import CSV</label>
      </div>
    </div>
  </div>
  
  <input type="file" class="btn btn-sm btn-outline-secondary" style="visibility:hidden;" id="customFile" data-action="change->users#importFile">

  <h3>All</h3>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Avatar</th>
          <th scope="col">Role</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody data-users-target="list"></tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">User <%= @user.fullname %></h1>
</div>
  
<h4 class="mb-3">Edit user</h4>
  
<%= render "form" %>

app/views/client/dashboard/index.html.erb
<div data-controller="users" >
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
  </div>

  <div class="row mb-1">
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Hello</strong>
          <h3 class="mb-0"><%= current_user.fullname %></h3>
          <div class="mb-1 text-muted"><%= current_user.email %></div>
          <a href="<%= edit_client_user_path(current_user) %>" class="stretched-link">Edit my account</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="<%= current_user.avatar_image %>" style="max-width: 500px">
        </div>
      </div>
    </div>
  </div>

app/views/client/users/_form.html.erb
<%= form_for @user, url: client_user_path(@user) do |f| %>
  <div class="row">
    <div class="form-outline mb-4 col-sm-12">
      <%= f.text_field :fullname, class: 'form-control form-control-lg', required: true %>
      <%= f.label :fullname, class: 'form-label' %>
    </div>
  </div>

  <div class="row">
    <div class="form-outline mb-4 col-sm-6">
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control form-control-lg', required: true %>
      <%= f.label :email, class: 'form-label' %>
    </div>

    <div class="form-outline mb-4 col-sm-6">
      <%= f.text_field :avatar_image, class: 'form-control form-control-lg', required: true %>
      <%= f.label :avatar_image, class: 'form-label' %>
    </div>
  </div>

  <div class="row">
    <div class="form-outline mb-4 col-sm-6">
      <% if @user.id.present? %>
        <%= f.password_field :password, autocomplete: "new-password", class: 'form-control form-control-lg' %>
      <% else %>
        <%= f.password_field :password, autocomplete: "new-password", class: 'form-control form-control-lg', required: true %>
      <% end %>
      <%= f.label :password, class: 'form-label' %> <%= "<i>(leave blank if you don't want to change it)</i>".html_safe if @user.id.present? %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
    </div>

    <div class="form-outline mb-4 col-sm-6">
      <% if @user.id.present? %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control form-control-lg' %>
      <% else %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control form-control-lg', required: true %>
      <% end %>
      
      <%= f.label :password_confirmation, class: 'form-label' %>
    </div>
  </div>
  <div class="pt-1 mb-4">
    <%= f.submit nil, class: 'btn btn-dark btn-lg btn-block' %>
  </div>
<% end %>

app/views/client/users/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">User <%= @user.fullname %></h1>
</div>
  
<h4 class="mb-3">Edit user</h4>
  
<%= render "form" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Test Rails</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-nav">
        <div class="nav-item text-nowrap">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link px-3" %>
        </div>
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="<%= current_user.admin? ? dashboard_index_path : '/client/dashboard' %>">
                  <span data-feather="home"></span>
                  Dashboard
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% elsif alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </main>
      </div>
    </div>

    
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% elsif alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>